services:
  onyx-server:
    image: ghcr.io/marcschuler/onyx-server:main
    # command: ["--emergency-grant-admin-power"] for resetting admin groups after you locked yoruself out
    ports:
      - "8080:8080"
    volumes:
      - onyx-data:/data/data
      - onyx-database:/data/database
      - onyx-cache:/data/cache

volumes:
  onyx-database:
  onyx-data:
  onyx-cache: