spring:
  application:
    name: webrtc-server
  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 1000
  datasource:
    url: jdbc:h2:file:${onyx.storage.path}/database
    driver-class-name: org.h2.Driver
    username: webrtc
    password: webrtc
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    de.marcschuler.webrtcserver: DEBUG

springdoc:
  api-docs:
    path: /openapi
  model-converters:
    polymorphic-converter:
      enabled: true

onyx:
  init:
    startup-wizzard: true
  auth:
    challenge:
      expiration: 1m
    jwt:
      expiration: 5m
      refresh: 4m
  storage:
    path: /data
    files: ${onyx.storage.path}/files

webrtc:
  config:
    ice:
      - urls: stun:stun.l.google.com:19302
      - urls: stun:stun.l.google.com:5349
      - urls: stun:stun1.l.google.com:3478
      - urls: stun:stun1.l.google.com:5349
      - urls: stun:stun2.l.google.com:19302
      - urls: stun:stun2.l.google.com:5349
      - urls: stun:stun3.l.google.com:3478
      - urls: stun:stun3.l.google.com:5349
      - urls: stun:stun4.l.google.com:19302
      - urls: stun:stun4.l.google.com:5349
      # - urls: turn:localhost:3478