spring:
  application:
    name: webrtc-server

  datasource:
    url: jdbc:h2:mem:webrtc
    driver-class-name: org.h2.Driver
    username: webrtc
    password: webrtc
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true


iris:
  auth:
    challenge:
      expiration: 1m
    jwt:
      expiration: 5m
      refresh: 4m

webrtc:
  config:
    ice:
      - urls: stun:stun.l.google.com:19302
      - urls: turn:localhost:3478