SET REFERENTIAL_INTEGRITY FALSE;


TRUNCATE TABLE MARKDOWN_MESSAGE_CONTENT;
TRUNCATE TABLE SERVER;
TRUNCATE TABLE SECTION;
TRUNCATE TABLE CHAT;
TRUNCATE TABLE CHANNEL;
TRUNCATE TABLE SERVER_GROUP;
TRUNCATE TABLE SERVER_GROUPS;
TRUNCATE TABLE SERVER_GROUP_ACCESS_POWERS;
TRUNCATE TABLE SERVER_USERS;
TRUNCATE TABLE SERVER_USERS_GROUPS;


SET REFERENTIAL_INTEGRITY TRUE;