SET REFERENTIAL_INTEGRITY FALSE;


TRUNCATE TABLE MARKDOWN_MESSAGE_CONTENT;
TRUNCATE TABLE SERVER;
TRUNCATE TABLE SERVER_DESCRIPTION;
TRUNCATE TABLE SECTION;
TRUNCATE TABLE CHAT;
TRUNCATE TABLE CHANNEL;
TRUNCATE TABLE SERVER_GROUP;
TRUNCATE TABLE SERVER_GROUPS;
TRUNCATE TABLE SERVER_USERS;
TRUNCATE TABLE SERVER_USERS_GROUPS;
TRUNCATE TABLE PERMISSION;
TRUNCATE TABLE PERMISSION_PERMISSIONS;
TRUNCATE TABLE SERVER_GROUP_PERMISSIONS;
TRUNCATE TABLE SERVER_SETTINGS;

SET REFERENTIAL_INTEGRITY TRUE;